#include <stdint.h>

// AHB1 Peripheral:
#define PERIPHERAL_BASE (0x40000000U)
#define AHB1_BASE_ADDR (PERIPHERAL_BASE + 0x20000U)
#define APB1_BASE_ADDR (PERIPHERAL_BASE + 0x00000U)

// RCC Peripheral:
#define RCC_BASE (AHB1_BASE_ADDR + 0x3800)

// RCC Peripheral Pointer:
#define RCC ((RCC_TypeDef*) RCC_BASE)

// RCC AHB1 Peripheral Clock Enable Bits:
#define RCC_AHB1ENR_GPIOAEN (0x00U)
#define RCC_AHB1ENR_GPIOGEN (0x06U)

// GPIO Peripheral Offsets:
#define GPIOA_BASE_OFFSET (0x0000U)
#define GPIOB_BASE_OFFSET (0x0400U)
#define GPIOC_BASE_OFFSET (0x0800U)
#define GPIOD_BASE_OFFSET (0x0C00U)
#define GPIOE_BASE_OFFSET (0x1000U)
#define GPIOF_BASE_OFFSET (0x1400U)
#define GPIOG_BASE_OFFSET (0x1800U)
#define GPIOH_BASE_OFFSET (0x1C00U)
#define GPIOI_BASE_OFFSET (0x2000U)
#define GPIOJ_BASE_OFFSET (0x2400U)
#define GPIOK_BASE_OFFSET (0x2800U)

// GPIO Peripheral Base Addresses:
#define GPIOA_BASE_ADDR (AHB1_BASE_ADDR + GPIOA_BASE_OFFSET)
#define GPIOB_BASE_ADDR (AHB1_BASE_ADDR + GPIOB_BASE_OFFSET)
#define GPIOC_BASE_ADDR (AHB1_BASE_ADDR + GPIOC_BASE_OFFSET)
#define GPIOD_BASE_ADDR (AHB1_BASE_ADDR + GPIOD_BASE_OFFSET)
#define GPIOE_BASE_ADDR (AHB1_BASE_ADDR + GPIOE_BASE_OFFSET)
#define GPIOF_BASE_ADDR (AHB1_BASE_ADDR + GPIOF_BASE_OFFSET)
#define GPIOG_BASE_ADDR (AHB1_BASE_ADDR + GPIOG_BASE_OFFSET)
#define GPIOH_BASE_ADDR (AHB1_BASE_ADDR + GPIOH_BASE_OFFSET)
#define GPIOI_BASE_ADDR (AHB1_BASE_ADDR + GPIOI_BASE_OFFSET)
#define GPIOJ_BASE_ADDR (AHB1_BASE_ADDR + GPIOJ_BASE_OFFSET)
#define GPIOK_BASE_ADDR (AHB1_BASE_ADDR + GPIOK_BASE_OFFSET)

// GPIO Peripheral Pointers:
#define GPIOA ((GPIO_TypeDef*) GPIOA_BASE_ADDR)
#define GPIOB ((GPIO_TypeDef*) GPIOB_BASE_ADDR)
#define GPIOC ((GPIO_TypeDef*) GPIOC_BASE_ADDR)
#define GPIOD ((GPIO_TypeDef*) GPIOD_BASE_ADDR)
#define GPIOE ((GPIO_TypeDef*) GPIOE_BASE_ADDR)
#define GPIOF ((GPIO_TypeDef*) GPIOF_BASE_ADDR)
#define GPIOG ((GPIO_TypeDef*) GPIOG_BASE_ADDR)
#define GPIOH ((GPIO_TypeDef*) GPIOH_BASE_ADDR)
#define GPIOI ((GPIO_TypeDef*) GPIOI_BASE_ADDR)
#define GPIOJ ((GPIO_TypeDef*) GPIOJ_BASE_ADDR)
#define GPIOK ((GPIO_TypeDef*) GPIOK_BASE_ADDR)

// I2C Peripheral Addresses:
#define I2C1_BASE (APB1_BASE_ADDR + 0x5400)
#define I2C2_BASE (APB1_BASE_ADDR + 0x5800)
#define I2C3_BASE (APB1_BASE_ADDR + 0x5C00)

// I2C Peripheral Pointers:
#define I2C1 ((I2C_TypeDef*) I2C1_BASE)
#define I2C2 ((I2C_TypeDef*) I2C2_BASE)
#define I2C3 ((I2C_TypeDef*) I2C3_BASE)